name: Matrix Workflow

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string

jobs:
  matrix-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run matrix job
        run: echo "matrix for ${{ inputs.platform }}" 