name: Matrix Workflow

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string

jobs:
  matrix-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run matrix job
        run: |
          if [ "${{ inputs.platform }}" = "ios" ]; then
            echo "matrix for ${{ inputs.platform }}"
          else
            echo "matrix for ${{ inputs.platform }}"
            exit 1
          fi
