name: Merge Queue Workflow

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, labeled]
  merge_group:
    types: [checks_requested]

jobs:
  build:
    if: ${{ github.event_name == 'merge_group' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ios, web]
    steps:
      - name: Run matrix job
        run: |
          echo "Running matrix for ${{ matrix.platform }}"
          if [ "${{ matrix.platform }}" = "ios" ]; then
            exit 1
          fi

  aggregate:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'merge_group' }}
    needs: [build]
    steps:
      - run: exit 0

  results:
    runs-on: ubuntu-latest
    needs: [build, aggregate]
    if: ${{ !cancelled() && github.event_name == 'merge_group' }}
    steps:
      - if: ${{ needs.build.result != 'skipped' && needs.aggregate.result != 'success' }}
        run: |
          echo "One of the jobs failed"
          exit 1
      - run: |
          echo "All jobs completed successfully"
          exit 0
