name: Merge Queue Workflow

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, labeled]
  merge_group:
    types: [checks_requested]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo testing
        run: echo "testing"

  build:
    needs: [job1]
    strategy:
      matrix:
        platform: [ios, web]
    uses: ./.github/workflows/matrix-workflow.yml
    with:
      platform: ${{ matrix.platform }}

  aggregate:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: exit 0

  results:
    runs-on: ubuntu-latest
    needs: [build, aggregate]
    if: ${{ !cancelled() }}
    steps:
      - if: ${{ needs.build.result != 'skipped' && needs.aggregate.result != 'success' }}
        run: |
          echo "One of the jobs failed"
          exit 1
      - run: |
          echo "All jobs completed successfully"
          exit 0